[workspace]
members = ["crates/dynamics", "crates/onboard_software", "crates/pyfrontend", "crates/simulation"]
resolver = "2"

[workspace.dependencies]
anise = "0.5"
hifitime = "4"
serde = { version = "1", features = ["derive"] }
rayon = "1"
math = { git = "https://github.com/anshgupta721/Azimuth.git", package = "math" }